import { ContentItem, Elements } from 'kentico-cloud-delivery';
import { CodeSample } from './code_sample';

/**
 * This class was generated by 'kentico-cloud-model-generator-utility' at Mon Jul 01 2019 14:28:20 GMT+0200 (GMT+02:00).
 *
 * Note: You can substitute 'ContentItem' type with another generated class.
 * Generator doesn't have this information available and so its up to you to define relationship between models.
 */
export class CodeSamples extends ContentItem {
    public codeSamples: Elements.LinkedItemsElement<CodeSample>;

    constructor() {
        super({
            propertyResolver: ((fieldName: string) => {
                if (fieldName === 'code_samples') {
                    return 'codeSamples';
                }
                return fieldName;
            }),
        });
    }
}
