import { ContentItem, Elements } from 'kentico-cloud-delivery';

/**
 * This class was generated by 'kentico-cloud-model-generator-utility' at Mon Jul 01 2019 14:28:20 GMT+0200 (GMT+02:00).
 *
 * Note: You can substitute 'ContentItem' type with another generated class.
 * Generator doesn't have this information available and so its up to you to define relationship between models.
 */
export class Image extends ContentItem {
    public border: Elements.MultipleChoiceElement;
    public zoomable: Elements.MultipleChoiceElement;
    public description: Elements.RichTextElement;
    public imageWidth: Elements.MultipleChoiceElement;
    public url: Elements.TextElement;
    public image: Elements.AssetsElement;

    constructor() {
        super({
            propertyResolver: ((fieldName: string) => {
                if (fieldName === 'image_width') {
                    return 'imageWidth';
                }
                return fieldName;
            }),
        });
    }
}
