import { ContentItem, Fields } from 'kentico-cloud-delivery';

/**
 * This class was generated by 'kentico-cloud-model-generator-utility' at Mon Jul 01 2019 14:28:20 GMT+0200 (GMT+02:00).
 *
 * Note: You can substitute 'ContentItem' type with another generated class.
 * Generator doesn't have this information available and so its up to you to define relationship between models.
 */
export class ZapiRequestBody extends ContentItem {
    public required: Fields.MultipleChoiceField;
    public schema: Fields.RichTextField;
    public example: Fields.TextField;
    public description: Fields.RichTextField;
    public apiReference: Fields.TaxonomyField;
    public mediaType: Fields.MultipleChoiceField;

    constructor() {
        super({
            propertyResolver: ((fieldName: string) => {
                if (fieldName === 'api_reference') {
                    return 'apiReference';
                }
                if (fieldName === 'media_type') {
                    return 'mediaType';
                }
                return fieldName;
            }),
        });
    }
}
