import {
    ContentItem,
    Elements,
} from 'kentico-cloud-delivery';

/**
 * This class was generated by 'kentico-cloud-model-generator-utility' at Wed Jul 17 2019 15:42:00 GMT+0200 (GMT+02:00).
 *
 * Note: You can substitute 'ContentItem' type with another generated class.
 * Generator doesn't have this information available and so its up to you to define relationship between models.
 */
export class ZapiSpecification extends ContentItem {
    public description: Elements.RichTextElement;
    public url: Elements.UrlSlugElement;
    public apiReference: Elements.TaxonomyElement;
    public title: Elements.TextElement;
    public license: ContentItem[];
    public categories: ContentItem[];
    public servers: Elements.RichTextElement;
    public termsOfService: Elements.TextElement;
    public version: Elements.TextElement;
    public security: ContentItem[];
    public contact: ContentItem[];

    constructor() {
        super({
            propertyResolver: ((fieldName: string) => {
                if (fieldName === 'api_reference') {
                    return 'apiReference';
                }
                if (fieldName === 'terms_of_service') {
                    return 'termsOfService';
                }
                return fieldName;
            }),
        });
    }
}
