import { ContentItem, Fields } from 'kentico-cloud-delivery';

/**
 * This class was generated by 'kentico-cloud-model-generator-utility' at Thu Jun 13 2019 13:54:14 GMT+0200 (GMT+02:00).
 *
 * Note: You can substitute 'ContentItem' type with another generated class. Generator doesn't have this information available
 * and so its up to you to define relationship between models.
 */
export class ZapiRequestBody extends ContentItem {
    public required: Fields.MultipleChoiceField;
    public schema: Fields.RichTextField;
    public example: Fields.TextField;
    public description: Fields.RichTextField;
    public contentType: Fields.TextField;
    constructor() {
        super({
            propertyResolver: ((fieldName: string) => {
                if (fieldName === 'content_type') {
                    return 'contentType';
                }
                return fieldName;
            })
        });
    }
}
