import {
    ContentItem,
    Elements,
} from 'kentico-cloud-delivery';

/**
 * This class was generated by 'kentico-cloud-model-generator-utility' at Mon Jul 01 2019 14:28:20 GMT+0200 (GMT+02:00).
 *
 * Note: You can substitute 'ContentItem' type with another generated class.
 * Generator doesn't have this information available and so its up to you to define relationship between models.
 */
export class ZapiSchemaAnyof extends ContentItem {
    public apiReference: Elements.TaxonomyElement;
    public commonSchemaObjectPropertyElementsWriteonly: Elements.MultipleChoiceElement;
    public schemas: ContentItem[];
    public commonSchemaObjectPropertyElementsReadonly: Elements.MultipleChoiceElement;
    public commonSchemaElementsExample: Elements.TextElement;
    public commonSchemaElementsDescription: Elements.RichTextElement;
    public commonSchemaElementsName: Elements.TextElement;
    public commonSchemaObjectPropertyElementsNullable: Elements.MultipleChoiceElement;

    constructor() {
        super({
            propertyResolver: ((fieldName: string) => {
                if (fieldName === 'api_reference') {
                    return 'apiReference';
                }
                if (fieldName === 'common_schema_object_property_elements__writeonly') {
                    return 'commonSchemaObjectPropertyElementsWriteonly';
                }
                if (fieldName === 'common_schema_object_property_elements__readonly') {
                    return 'commonSchemaObjectPropertyElementsReadonly';
                }
                if (fieldName === 'common_schema_elements__example') {
                    return 'commonSchemaElementsExample';
                }
                if (fieldName === 'common_schema_elements__description') {
                    return 'commonSchemaElementsDescription';
                }
                if (fieldName === 'common_schema_elements__name') {
                    return 'commonSchemaElementsName';
                }
                if (fieldName === 'common_schema_object_property_elements__nullable') {
                    return 'commonSchemaObjectPropertyElementsNullable';
                }
                return fieldName;
            }),
        });
    }
}
