import { ContentItem, Fields } from 'kentico-cloud-delivery';

/**
 * This class was generated by 'kentico-cloud-model-generator-utility' at Mon Jul 01 2019 14:28:20 GMT+0200 (GMT+02:00).
 *
 * Note: You can substitute 'ContentItem' type with another generated class.
 * Generator doesn't have this information available and so its up to you to define relationship between models.
 */
export class ZapiSecurityScheme extends ContentItem {
    public bearerFormat: Fields.TextField;
    public apiReference: Fields.TaxonomyField;
    public apiKeyName: Fields.TextField;
    public name: Fields.TextField;
    public scheme: Fields.TextField;
    public description: Fields.RichTextField;
    public type: Fields.MultipleChoiceField;
    public apiKeyLocation: Fields.MultipleChoiceField;

    constructor() {
        super({
            propertyResolver: ((fieldName: string) => {
                if (fieldName === 'bearer_format') {
                    return 'bearerFormat';
                }
                if (fieldName === 'api_reference') {
                    return 'apiReference';
                }
                if (fieldName === 'api_key_name') {
                    return 'apiKeyName';
                }
                if (fieldName === 'api_key_location') {
                    return 'apiKeyLocation';
                }
                return fieldName;
            }),
        });
    }
}
