import {
    ContentItem,
    Elements,
} from 'kentico-cloud-delivery';
import { ZapiPathOperation } from './zapi_path_operation';

/**
 * This class was generated by 'kentico-cloud-model-generator-utility' at Wed Jul 17 2019 15:42:00 GMT+0200 (GMT+02:00).
 *
 * Note: You can substitute 'ContentItem' type with another generated class.
 * Generator doesn't have this information available and so its up to you to define relationship between models.
 */
export class ZapiCategory extends ContentItem {
    public description: Elements.RichTextElement;
    public url: Elements.UrlSlugElement;
    public apiReference: Elements.TaxonomyElement;
    public pathOperations: Elements.LinkedItemsElement<ZapiPathOperation>;
    public name: Elements.TextElement;

    constructor() {
        super({
            propertyResolver: ((fieldName: string) => {
                if (fieldName === 'api_reference') {
                    return 'apiReference';
                }
                if (fieldName === 'path_operations') {
                    return 'pathOperations';
                }
                return fieldName;
            }),
        });
    }
}
