import {
    ContentItem,
    Elements,
} from 'kentico-cloud-delivery';

/**
 * This class was generated by 'kentico-cloud-model-generator-utility' at Mon Jul 01 2019 14:28:20 GMT+0200 (GMT+02:00).
 *
 * Note: You can substitute 'ContentItem' type with another generated class.
 * Generator doesn't have this information available and so its up to you to define relationship between models.
 */
export class ZapiSecurityScheme extends ContentItem {
    public bearerFormat: Elements.TextElement;
    public apiReference: Elements.TaxonomyElement;
    public apiKeyName: Elements.TextElement;
    public name: Elements.TextElement;
    public scheme: Elements.TextElement;
    public description: Elements.RichTextElement;
    public type: Elements.MultipleChoiceElement;
    public apiKeyLocation: Elements.MultipleChoiceElement;

    constructor() {
        super({
            propertyResolver: ((fieldName: string) => {
                if (fieldName === 'bearer_format') {
                    return 'bearerFormat';
                }
                if (fieldName === 'api_reference') {
                    return 'apiReference';
                }
                if (fieldName === 'api_key_name') {
                    return 'apiKeyName';
                }
                if (fieldName === 'api_key_location') {
                    return 'apiKeyLocation';
                }
                return fieldName;
            }),
        });
    }
}
