import { ContentItem, Elements } from 'kentico-cloud-delivery';

import { ZapiParameter } from './zapi_parameter';

/**
 * Generated by 'kentico-cloud-model-generator-utility@2.1.0'
 * Timestamp: Thu Sep 05 2019 13:36:04 GMT+0200 (GMT+02:00)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class ZapiResponse extends ContentItem {
  public description: Elements.RichTextElement;
  public headers: Elements.LinkedItemsElement<ZapiParameter>;
  public schema: Elements.RichTextElement;
  public example: Elements.TextElement;
  public apiReference: Elements.TaxonomyElement;
  public mediaType: Elements.MultipleChoiceElement;
  public httpStatus: Elements.MultipleChoiceElement;

  constructor() {
    super({
      propertyResolver: ((elementName: string) => {
        if (elementName === 'api_reference') {
          return 'apiReference';
        }
        if (elementName === 'media_type') {
          return 'mediaType';
        }
        if (elementName === 'http_status') {
          return 'httpStatus';
        }
        return elementName;
      })
    });
  }
}
