import {
    ContentItem,
    Elements,
} from 'kentico-cloud-delivery';

import { ZapiAllSchemas } from '../processing/schemas';

/**
 * This class was generated by 'kentico-cloud-model-generator-utility' at Mon Jul 01 2019 14:28:20 GMT+0200 (GMT+02:00).
 *
 * Note: You can substitute 'ContentItem' type with another generated class.
 * Generator doesn't have this information available and so its up to you to define relationship between models.
 */
export class ZapiSchemaOneof extends ContentItem {
    public discriminator: Elements.RichTextElement;
    public schemas: Elements.LinkedItemsElement<ZapiAllSchemas>;
    public apiReference: Elements.TaxonomyElement;
    public commonSchemaElementsExample: Elements.TextElement;
    public commonSchemaElementsDescription: Elements.RichTextElement;
    public commonSchemaElementsName: Elements.TextElement;

    constructor() {
        super({
            propertyResolver: ((fieldName: string) => {
                if (fieldName === 'api_reference') {
                    return 'apiReference';
                }
                if (fieldName === 'common_schema_elements__example') {
                    return 'commonSchemaElementsExample';
                }
                if (fieldName === 'common_schema_elements__description') {
                    return 'commonSchemaElementsDescription';
                }
                if (fieldName === 'common_schema_elements__name') {
                    return 'commonSchemaElementsName';
                }
                return fieldName;
            }),
        });
    }
}
