import {
    ContentItem,
    Elements,
} from 'kentico-cloud-delivery';

/**
 * This class was generated by 'kentico-cloud-model-generator-utility' at Wed Jul 17 2019 15:42:00 GMT+0200 (GMT+02:00).
 *
 * Note: You can substitute 'ContentItem' type with another generated class.
 * Generator doesn't have this information available and so its up to you to define relationship between models.
 */
export class ZapiPathOperation extends ContentItem {
    public description: Elements.RichTextElement;
    public codeSamples: ContentItem[];
    public path: Elements.TextElement;
    public requestBody: Elements.RichTextElement;
    public apiReference: Elements.TaxonomyElement;
    public responses: Elements.RichTextElement;
    public pathOperation: Elements.TaxonomyElement;
    public deprecated: Elements.MultipleChoiceElement;
    public url: Elements.UrlSlugElement;
    public name: Elements.TextElement;
    public parameters: ContentItem[];

    constructor() {
        super({
            propertyResolver: ((fieldName: string) => {
                if (fieldName === 'code_samples') {
                    return 'codeSamples';
                }
                if (fieldName === 'request_body') {
                    return 'requestBody';
                }
                if (fieldName === 'api_reference') {
                    return 'apiReference';
                }
                if (fieldName === 'path_operation') {
                    return 'pathOperation';
                }
                return fieldName;
            }),
        });
    }
}
