import { ContentItem, Fields } from 'kentico-cloud-delivery';

/**
 * This class was generated by 'kentico-cloud-model-generator-utility' at Mon Jul 01 2019 14:28:20 GMT+0200 (GMT+02:00).
 *
 * Note: You can substitute 'ContentItem' type with another generated class.
 * Generator doesn't have this information available and so its up to you to define relationship between models.
 */
export class ZapiSchemaString extends ContentItem {
    public format: Fields.TextField;
    public acceptedValues: Fields.TextField;
    public commonSchemaObjectPropertyElementsWriteonly: Fields.MultipleChoiceField;
    public minlength: Fields.NumberField;
    public defaultValue: Fields.TextField;
    public apiReference: Fields.TaxonomyField;
    public commonSchemaObjectPropertyElementsReadonly: Fields.MultipleChoiceField;
    public commonSchemaElementsExample: Fields.TextField;
    public commonSchemaElementsDescription: Fields.RichTextField;
    public maxlength: Fields.NumberField;
    public commonSchemaElementsName: Fields.TextField;
    public commonSchemaObjectPropertyElementsNullable: Fields.MultipleChoiceField;

    constructor() {
        super({
            propertyResolver: ((fieldName: string) => {
                if (fieldName === 'accepted_values') {
                    return 'acceptedValues';
                }
                if (fieldName === 'common_schema_object_property_elements__writeonly') {
                    return 'commonSchemaObjectPropertyElementsWriteonly';
                }
                if (fieldName === 'default_value') {
                    return 'defaultValue';
                }
                if (fieldName === 'api_reference') {
                    return 'apiReference';
                }
                if (fieldName === 'common_schema_object_property_elements__readonly') {
                    return 'commonSchemaObjectPropertyElementsReadonly';
                }
                if (fieldName === 'common_schema_elements__example') {
                    return 'commonSchemaElementsExample';
                }
                if (fieldName === 'common_schema_elements__description') {
                    return 'commonSchemaElementsDescription';
                }
                if (fieldName === 'common_schema_elements__name') {
                    return 'commonSchemaElementsName';
                }
                if (fieldName === 'common_schema_object_property_elements__nullable') {
                    return 'commonSchemaObjectPropertyElementsNullable';
                }
                return fieldName;
            }),
        });
    }
}
