import {
    ContentItem,
    Fields,
} from 'kentico-cloud-delivery';

/**
 * This class was generated by 'kentico-cloud-model-generator-utility' at Mon Jul 01 2019 14:28:20 GMT+0200 (GMT+02:00).
 *
 * Note: You can substitute 'ContentItem' type with another generated class.
 * Generator doesn't have this information available and so its up to you to define relationship between models.
 */
export class ZapiParameter extends ContentItem {
    public explode: Fields.MultipleChoiceField;
    public example: Fields.TextField;
    public deprecated: Fields.MultipleChoiceField;
    public apiReference: Fields.TaxonomyField;
    public location: Fields.MultipleChoiceField;
    public schema: ContentItem[];
    public style: Fields.MultipleChoiceField;
    public name: Fields.TextField;
    public required: Fields.MultipleChoiceField;
    public description: Fields.RichTextField;

    constructor() {
        super({
            propertyResolver: ((fieldName: string) => {
                if (fieldName === 'api_reference') {
                    return 'apiReference';
                }
                return fieldName;
            }),
        });
    }
}
