import { ContentItem, Elements } from 'kentico-cloud-delivery';

/**
 * Generated by 'kentico-cloud-model-generator-utility@2.1.0'
 * Timestamp: Thu Sep 05 2019 13:36:04 GMT+0200 (GMT+02:00)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class ZapiSchemaBoolean extends ContentItem {
  public commonSchemaObjectPropertyElementsWriteonly: Elements.MultipleChoiceElement;
  public apiReference: Elements.TaxonomyElement;
  public commonSchemaObjectPropertyElementsReadonly: Elements.MultipleChoiceElement;
  public commonSchemaElementsExample: Elements.TextElement;
  public commonSchemaElementsDescription: Elements.RichTextElement;
  public commonSchemaElementsName: Elements.TextElement;
  public commonSchemaObjectPropertyElementsNullable: Elements.MultipleChoiceElement;

  constructor() {
    super({
      propertyResolver: ((elementName: string) => {
        if (elementName === 'common_schema_object_property_elements__writeonly') {
          return 'commonSchemaObjectPropertyElementsWriteonly';
        }
        if (elementName === 'api_reference') {
          return 'apiReference';
        }
        if (elementName === 'common_schema_object_property_elements__readonly') {
          return 'commonSchemaObjectPropertyElementsReadonly';
        }
        if (elementName === 'common_schema_elements__example') {
          return 'commonSchemaElementsExample';
        }
        if (elementName === 'common_schema_elements__description') {
          return 'commonSchemaElementsDescription';
        }
        if (elementName === 'common_schema_elements__name') {
          return 'commonSchemaElementsName';
        }
        if (elementName === 'common_schema_object_property_elements__nullable') {
          return 'commonSchemaObjectPropertyElementsNullable';
        }
        return elementName;
      })
    });
  }
}
