import { ContentItem, Elements } from 'kentico-cloud-delivery';

import { ZapiCategory } from './zapi__category';
import { ZapiContact } from './zapi_contact';
import { ZapiLicense } from './zapi_license';
import { ZapiSecurityScheme } from './zapi_security_scheme';

/**
 * Generated by 'kentico-cloud-model-generator-utility@2.1.0'
 * Timestamp: Thu Sep 05 2019 13:36:04 GMT+0200 (GMT+02:00)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class ZapiSpecification extends ContentItem {
  public description: Elements.RichTextElement;
  public url: Elements.UrlSlugElement;
  public apiReference: Elements.TaxonomyElement;
  public title: Elements.TextElement;
  public license: Elements.LinkedItemsElement<ZapiLicense>;
  public categories: Elements.LinkedItemsElement<ZapiCategory>;
  public servers: Elements.RichTextElement;
  public termsOfService: Elements.TextElement;
  public version: Elements.TextElement;
  public security: Elements.LinkedItemsElement<ZapiSecurityScheme>;
  public contact: Elements.LinkedItemsElement<ZapiContact>;
  public apiStatus: Elements.MultipleChoiceElement;

  constructor() {
    super({
      propertyResolver: ((elementName: string) => {
        if (elementName === 'api_reference') {
          return 'apiReference';
        }
        if (elementName === 'terms_of_service') {
          return 'termsOfService';
        }
        if (elementName === 'api_status') {
          return 'apiStatus';
        }
        return elementName;
      })
    });
  }
}
