import { ContentItem, Fields } from 'kentico-cloud-delivery';

/**
 * This class was generated by 'kentico-cloud-model-generator-utility' at Mon Jul 01 2019 14:28:20 GMT+0200 (GMT+02:00).
 *
 * Note: You can substitute 'ContentItem' type with another generated class.
 * Generator doesn't have this information available and so its up to you to define relationship between models.
 */
export class ZapiSpecification extends ContentItem {
    public description: Fields.RichTextField;
    public url: Fields.UrlSlugField;
    public apiReference: Fields.TaxonomyField;
    public title: Fields.TextField;
    public license: ContentItem[];
    public categories: ContentItem[];
    public pathOperations: ContentItem[];
    public servers: Fields.RichTextField;
    public termsOfService: Fields.TextField;
    public version: Fields.TextField;
    public security: ContentItem[];
    public contact: ContentItem[];

    constructor() {
        super({
            propertyResolver: ((fieldName: string) => {
                if (fieldName === 'api_reference') {
                    return 'apiReference';
                }
                if (fieldName === 'path_operations') {
                    return 'pathOperations';
                }
                if (fieldName === 'terms_of_service') {
                    return 'termsOfService';
                }
                return fieldName;
            }),
        });
    }
}
