import {
    ContentItem,
    Elements,
} from 'kentico-cloud-delivery';

/**
 * This class was generated by 'kentico-cloud-model-generator-utility' at Mon Jul 01 2019 14:28:20 GMT+0200 (GMT+02:00).
 *
 * Note: You can substitute 'ContentItem' type with another generated class.
 * Generator doesn't have this information available and so its up to you to define relationship between models.
 */
export class ZapiDiscriminator extends ContentItem {
    public mapping: Elements.RichTextElement;
    public propertyName: Elements.TextElement;

    constructor() {
        super({
            propertyResolver: ((fieldName: string) => {
                if (fieldName === 'property_name') {
                    return 'propertyName';
                }
                return fieldName;
            }),
        });
    }
}
