import { ContentItem, Elements } from 'kentico-cloud-delivery';

import { ZapiAllSchemas } from '../processing/schemas';

/**
 * Generated by 'kentico-cloud-model-generator-utility@2.1.0'
 * Timestamp: Thu Sep 05 2019 13:36:04 GMT+0200 (GMT+02:00)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class ZapiDiscriminatorMapItem extends ContentItem {
  public schema: Elements.LinkedItemsElement<ZapiAllSchemas>;
  public discriminatorValue: Elements.TextElement;

  constructor() {
    super({
      propertyResolver: ((elementName: string) => {
        if (elementName === 'discriminator_value') {
          return 'discriminatorValue';
        }
        return elementName;
      })
    });
  }
}
