import {
    ContentItem,
    Elements,
} from 'kentico-cloud-delivery';
import { ZapiParameter } from './zapi_parameter';

/**
 * This class was generated by 'kentico-cloud-model-generator-utility' at Mon Jul 01 2019 14:28:20 GMT+0200 (GMT+02:00).
 *
 * Note: You can substitute 'ContentItem' type with another generated class.
 * Generator doesn't have this information available and so its up to you to define relationship between models.
 */
export class ZapiResponse extends ContentItem {
    public description: Elements.RichTextElement;
    public headers: Elements.LinkedItemsElement<ZapiParameter>;
    public schema: Elements.RichTextElement;
    public example: Elements.TextElement;
    public apiReference: Elements.TaxonomyElement;
    public mediaType: Elements.MultipleChoiceElement;
    public httpStatus: Elements.MultipleChoiceElement;

    constructor() {
        super({
            propertyResolver: ((fieldName: string) => {
                if (fieldName === 'api_reference') {
                    return 'apiReference';
                }
                if (fieldName === 'media_type') {
                    return 'mediaType';
                }
                if (fieldName === 'http_status') {
                    return 'httpStatus';
                }
                return fieldName;
            }),
        });
    }
}
