import {
    ContentItem,
    Elements,
} from 'kentico-cloud-delivery';

/**
 * This class was generated by 'kentico-cloud-model-generator-utility' at Wed Jul 17 2019 15:42:00 GMT+0200 (GMT+02:00).
 *
 * Note: You can substitute 'ContentItem' type with another generated class.
 * Generator doesn't have this information available and so its up to you to define relationship between models.
 */
export class ZapiSchemaObject extends ContentItem {
    public required: Elements.TextElement;
    public apiReference: Elements.TaxonomyElement;
    public commonSchemaElementsExample: Elements.TextElement;
    public commonSchemaElementsDescription: Elements.RichTextElement;
    public commonSchemaElementsName: Elements.TextElement;
    public properties: Elements.RichTextElement;
    public additionalProperties: Elements.RichTextElement;

    constructor() {
        super({
            propertyResolver: ((fieldName: string) => {
                if (fieldName === 'api_reference') {
                    return 'apiReference';
                }
                if (fieldName === 'common_schema_elements__example') {
                    return 'commonSchemaElementsExample';
                }
                if (fieldName === 'common_schema_elements__description') {
                    return 'commonSchemaElementsDescription';
                }
                if (fieldName === 'common_schema_elements__name') {
                    return 'commonSchemaElementsName';
                }
                if (fieldName === 'additional_properties') {
                    return 'additionalProperties';
                }
                return fieldName;
            }),
        });
    }
}
